name: TriggerHappy - Discussion Moderation Tool

on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]

jobs:
  moderate:
    runs-on: ubuntu-latest
    steps:
      - uses: erstarr/TriggerHappy@main
        with:
          github_token: ${{ secrets.CROSS_REPO_TOKEN }}
          storage_repo: your-org/.github