# Users who can use /close <reason>
closers:
  # - bob is implicit since bob is a moderator
  - ellie
  - allison

# Users who can use /strike [@user]
strikers:
  # - bob is implicit since bob is a moderator
  - alice

# Users who can use /ban @user <reason> as well as do perform any other command
moderators:
  - bob