# Users who can use /close <reason>
# Users who can use /strike
strikers:
  # - bob is implicit since bob is a moderator
  # - allison is implicit since allison can also close
  - alice

closers:
  # - bob is implicit since bob is a moderator
  - allison


# Users who can use /ban <reason>, /unban, close/open discussions, as well as do perform any other command
moderators:
  - bob