# Users who can use strike commands
strikers:
  # - bob is implicit since bob is a moderator
  # - allison is implicit since allison can also close
  - alice

# Users who can use close/open commands  as well as all the commands of lower permissions
closers:
  # - bob is implicit since bob is a moderator
  - allison


# Users who can use ban/open commands as well as all the commands of lower permissions
moderators:
  - bob